development:
  adapter: postgresql
  encoding: unicode
  database: d3tt68mpgesust
  pool: 5
  username: cywmhnbbcrjynw
  password: b223433c074114976e3ead0bc443841e00060f97d96efb6536dfddbf4c7ef813
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: d3tt68mpgesust
  pool: 5
  username: cywmhnbbcrjynw
  password: b223433c074114976e3ead0bc443841e00060f97d96efb6536dfddbf4c7ef813
  port: 5432



production:
  adapter: postgresql 
  encoding: unicode
  database: d3tt68mpgesust
  pool: 5
  username: cywmhnbbcrjynw
  password: b223433c074114976e3ead0bc443841e00060f97d96efb6536dfddbf4c7ef813
  port: 5432